@startuml
'https://plantuml.com/class-diagram

class Pawn extends Piece
class Knight extends Piece
class Bishop extends Piece
class Rook extends Piece
class Queen extends Piece
class King extends Piece
interface StrategyMovement



interface IPlayerObserver
{
    +reactTo() : void
}

interface IBoardObserver
{
    +reactTo() : void
}
class BoardObserver implements IBoardObserver
{
    +reactTo(board : Board) : void
}
class PlayerObserver implements IPlayerObserver
{
    +reactTo(player : Player) : void
}


enum Color {
    WHITE
    BLACK
}

class Board {
    -board int[]
    -pieces : List<Piece>
    #observers : List<BoardObserver>

    +Board() : Board
    +getPieces() : List<Piece>
    +getPieceFromPosition(position : int) : Piece
    +addPieceToList(piece : Piece) : void
    +removePieceFromList(piece : Piece) : void
    +isValidMove(piece : Piece, newPosition : int) : boolean
    -pathIsFree(piece : Piece, newPosition : int)
    +isPathFreeOnXY(piece : Piece, newPosition : int)
    +isPathFreeOnRay(piece : Piece, newPosition : int)
    +isPostionOccupied(position : int) : boolean
    +isInCheck(color : Color)
    +getKing(color : Color)
    +isPat(color : Color)
    +moveWillCauseCheck(piece : Piece, newPosition : int)
    +initBoard()

    +addObserver(observer : BoardObserver) : void
    +notifyObserver() : void
}

class Player {
    -name : String
    -urTurn : boolean
    -capturedPiece : List<Piece>
    -color : Color
    #observers : List<PlayerObserver>

    +Player(Color : color, String : name , urTurn : boolean)
    +getColor() : Color
    +getCapturedPieces() : List<Piece>
    +isUrTurn() : boolean
    +changeTurn() : void
    +isUrTurn() : boolean
    +addCapturedPieces(piece : Piece) : void
    +move(piece : Piece, newPosition : int) : void

    +addObserver(observer : PlayerObserver) : void
    +notifyObserver() : void
}

class GameManager{
    -whitePlayer : Player
    -blackPlayer : Player
    -lastCommand : ICommand
    -commandFactory : CommandFactory
    -board : Board

    +GameManager(board : Board, whitePlayer : Player, blackPlayer : Player, lastCommand : ICommand, commandFactory : CommandFactory)
    +getCurrentPlayer() : Player
    +executeCommand(String command) : void
    +undoCommand() : void
    +promotePawn(pawn : Pawn, newPiece : Piece)
    +isPat() : boolean
    +isPlayerInCheckMate() : boolean
    +isPlayerInCheck() : boolean
}



class CommandFactory {
    +CommandFactory(board : Board)
    +createCommand() : ICommand
}

interface ICommand{
    execute() : void
    undo() : void
}

class CommandMaker {
    -oldPosition : int
    -newPosition : int
    -player : Player
    -piece : Piece
    -board : Board
}

class MoveCommand {
}
class AttackCommand {
}
class RookKingCommand {
}

class PieceFactory {
    -instance : PieceFactory

    -PieceFactory()
    +createInstance() : PieceFactory
    +createPawn() : Piece
    +createKnight() : Piece
    +createBishop() : Piece
    +createRook() : Piece
    +createQueen() : Piece
    +createKing() : Piece
}
class Piece {
    -color : Color
    -position : int
    #Piece(color : Color, position : int)
    +getPosition() : int
    +setPosition(position : int)
    +getColor() : Color
    +isValidMove(newPosition : int) : boolean
    +canCapturePiece(piece : Piece) : boolean
}
class Pawn {
    -isPromoted : boolean
    -isEmpassant : boolean
    -hasMovedOnce : boolean
}
class King {
    -instance : King
    -isChecked : boolean
    -hasMovedOnce : boolean
    -King()
    +createInstance() : King
}
class Queen {
}
class Knight {
}
class Bishop {
}
class Rook {
}

Piece "1" *-- "1" StrategyMovement : contains
Piece "1" *-- "1" Color : contains
Player "1" *-- "1" Color : contains

StrategyMovement <|-- StrategyMovementPawn
StrategyMovement <|-- StrategyMovementKnight
StrategyMovement <|-- StrategyMovementBishop
StrategyMovement <|-- StrategyMovementRook
StrategyMovement <|-- StrategyMovementQueen
StrategyMovement <|-- StrategyMovementKing
Player --o Piece
Board --* CommandFactory
CommandFactory --[dashed]-> ICommand
ICommand --* GameManager
CommandFactory --* GameManager
Board --* GameManager
Player --* GameManager
CommandMaker *-- Board
CommandMaker *-- Piece
AttackCommand --[dashed]-> CommandMaker
MoveCommand --[dashed]-> CommandMaker
RookKingCommand --[dashed]-> CommandMaker

@enduml